name: rethinkdb
author: William Welch <billywelch@gmail.com>
version: 0.1.0
homepage: https://github.com/billysometimes/rethinkdb
description: Dart driver for RethinkDB.
documentation: https://github.com/billysometimes/rethinkdb
dependencies:
  logging: any
  protobuf:
    git: https://github.com/dart-lang/dart-protobuf.git
    version: '>=0.1.0'
dev_dependencies:
  unittest: '>=0.5.20'
