name: rethinkdb_driver
authors:
- Dave Bettin <me@davebettin.com>
- William Welch <billywelch@gmail.com>
version: 0.2.0
homepage: https://github.com/billysometimes/rethinkdb
description: Dart driver for RethinkDB.
documentation: https://github.com/billysometimes/rethinkdb
dependencies:
  logging: '>=0.9.1+1'
  protobuf: '>=0.3.3'
dev_dependencies:
  unittest: '>=0.9.3'
